### ISSUE TITLE
docker install error

### ISSUE THREAD

**Issue by waytai** [fkie-cad/FACT_docker#19]
```
[2022-05-06 08:31:42][install][INFO]: Installing variety/variety
Traceback (most recent call last):
  File "/opt/FACT_core/src/install.py", line 183, in <module>
    install()
  File "/opt/FACT_core/src/install.py", line 151, in install
    install_fact_components(args, distribution, none_chosen, skip_docker)
  File "/opt/FACT_core/src/install.py", line 165, in install_fact_components
    common(distribution)
  File "/opt/FACT_core/src/install/common.py", line 65, in main
    install_github_project('variety/variety', ['git checkout 2f4d815', 'mv -f variety.js ../../bin/', 'mv -f spec ../../bin/'])
  File "/opt/FACT_core/src/helperFunctions/install.py", line 163, in install_github_project
    _checkout_github_project(project_path, folder_name)
  File "/opt/FACT_core/src/helperFunctions/install.py", line 181, in _checkout_github_project
    raise InstallationError('Cloning from github failed for project {}\n {}'.format(github_path, clone_url))
helperFunctions.install.InstallationError: Cloning from github failed for project variety/variety
 https://www.github.com/variety/variety
The command '/bin/sh -c FACT_INSTALLER_SKIP_DOCKER=y /opt/FACT_core/src/install.py' returned a non-zero code: 1
```

**Comment by waytai** [comment]
Traceback (most recent call last):
  File "/opt/FACT_core/src/install.py", line 183, in <module>
    install()
  File "/opt/FACT_core/src/install.py", line 151, in install
    install_fact_components(args, distribution, none_chosen, skip_docker)
  File "/opt/FACT_core/src/install.py", line 165, in install_fact_components
    common(distribution)
  File "/opt/FACT_core/src/install/common.py", line 59, in main
    install_pip_packages(PIP_DEPENDENCIES)
  File "/opt/FACT_core/src/helperFunctions/install.py", line 262, in install_pip_packages
    run_cmd_with_logging(command, silent=True)
  File "/opt/FACT_core/src/helperFunctions/install.py", line 219, in run_cmd_with_logging
    raise err
  File "/opt/FACT_core/src/helperFunctions/install.py", line 213, in run_cmd_with_logging
    subprocess.run(cmd_, stdout=PIPE, stderr=PIPE, encoding='UTF-8', shell=shell, check=True, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', '-EH', 'pip3', 'install', '-U', 'git+https://github.com/fkie-cad/common_helper_filter.git', '--prefer-binary']' returned non-zero exit status 1.
The command '/bin/sh -c FACT_INSTALLER_SKIP_DOCKER=y /opt/FACT_core/src/install.py' returned a non-zero code: 1

**Comment by waytai** [comment]
Traceback (most recent call last):
  File "/opt/FACT_core/src/install.py", line 183, in <module>
    install()
  File "/opt/FACT_core/src/install.py", line 151, in install
    install_fact_components(args, distribution, none_chosen, skip_docker)
  File "/opt/FACT_core/src/install.py", line 167, in install_fact_components
    frontend(skip_docker, not args.no_radare, args.nginx, distribution)
  File "/opt/FACT_core/src/install/frontend.py", line 183, in main
    _install_css_and_js_files()
  File "/opt/FACT_core/src/install/frontend.py", line 122, in _install_css_and_js_files
    wget_static_web_content('https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js', '.', [], 'angularJS')
  File "/opt/FACT_core/src/install/frontend.py", line 33, in wget_static_web_content
    raise InstallationError('Failed to fetch resource at {}\n{}'.format(url, wget_process.stdout))
helperFunctions.install.InstallationError: Failed to fetch resource at https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
--2022-05-06 10:24:33--  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Resolving ajax.googleapis.com (ajax.googleapis.com)... 142.251.42.234
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:26:47--  (try: 2)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:28:56--  (try: 3)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:31:06--  (try: 4)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:33:17--  (try: 5)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:35:30--  (try: 6)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:37:43--  (try: 7)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:39:57--  (try: 8)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:42:13--  (try: 9)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:44:29--  (try:10)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:46:46--  (try:11)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:49:03--  (try:12)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:51:20--  (try:13)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:53:38--  (try:14)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:55:55--  (try:15)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 10:58:12--  (try:16)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 11:00:29--  (try:17)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 11:02:47--  (try:18)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 11:05:04--  (try:19)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Retrying.

--2022-05-06 11:07:21--  (try:20)  https://ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js
Connecting to ajax.googleapis.com (ajax.googleapis.com)|142.251.42.234|:443... failed: Connection timed out.
Giving up.

**Comment by jstucke** [comment]
Hi, do you maybe work behind a proxy or do you have internet connection problems? All errors you posted indicate problems with your connection.

**Comment by waytai** [comment]
yes ,I am in china, maybe that is
