### ISSUE TITLE
FACT_docker is not compatible with FACT_core any more

### ISSUE THREAD

**Issue by KingRumn** [fkie-cad/FACT_docker#26]
Since commit abc9f50 (replaced mongo in intercom with redis + completely removed mongo), mongo has been removed, while FACT_docker is still not upgraded. The generated docker image can not run any more.
Error occured:

python3: can't open file '/opt/FACT_core/src/init_database.py': [Errno 2] No such file or directory.

**Comment by maringuu** [comment]
See #20
