### ISSUE TITLE
Support docker behind a proxy

### ISSUE THREAD

**Issue by afeng2016-s** [fkie-cad/FACT_docker#37]
./start.py pull

![image](https://github.com/fkie-cad/FACT_docker/assets/85676107/fc26ba04-6535-4fa9-854d-5fc9f8bd1e74)

Access 104.18.124.25:443
![image](https://github.com/fkie-cad/FACT_docker/assets/85676107/584b31bf-8403-453d-9d7b-d2d64110a9ee)

**Comment by maringuu** [comment]
Seems like something is wrong with you docker configuration.
The image does nothing but use `docker pull`.
Are you behind a proxy?
Then you have to configure docker on you host to use this proxy.
