### ISSUE TITLE
docker-compose up error

### ISSUE THREAD

**Issue by yujack008** [fkie-cad/FACT_docker#38]
ijiami@ijiami-All-Series:~/newdisk/iot/FACT_docker$ docker-compose up
fact_docker_database_1 is up-to-date
fact_docker_redis_1 is up-to-date
Creating fact_docker_fact-frontend_1 ... error
Creating fact_docker_fact-backend_1  ... 

Creating fact_docker_fact-backend_1  ... error

ERROR: for fact_docker_fact-backend_1  Cannot create container for service fact-backend: invalid mount config for type "bind": bind source path does not exist: /tmp/fact-docker-mount-base-dir

ERROR: for fact-frontend  Cannot create container for service fact-frontend: invalid mount config for type "bind": bind source path does not exist: /tmp/fact-docker-mount-base-dir

ERROR: for fact-backend  Cannot create container for service fact-backend: invalid mount config for type "bind": bind source path does not exist: /tmp/fact-docker-mount-base-dir
ERROR: Encountered errors while bringing up the project.
ijiami@ijiami-All-Series:~/newdisk/iot/FACT_docker$

**Comment by yujack008** [comment]
ijiami@ijiami-All-Series:~/newdisk/iot/FACT_docker$ ls -al /tmp/fact-docker-mount-base-dir
total 96
drwxrwx---  2 ijiami docker  4096 Aug 11 16:07 .
drwxrwxrwt 23 root   root   90112 Aug 14 12:16 ..

**Comment by maringuu** [comment]
I can't reproduce.
Please try again and provide a detailted description of your system and most importantly what you did.
