### ISSUE TITLE
FACT_docker install show that "Your Distribution (alpine 3.15.6) is not supported.

### ISSUE THREAD

**Issue by goant** [fkie-cad/FACT_docker#39]
when I use FACT_docker to install:
![image](https://github.com/fkie-cad/FACT_docker/assets/11664059/dbbcad09-7beb-490a-ade1-52a9a15dfb43)
it shows:Your Distribution (alpine 3.15.6) is not supported. FACT Installer requires Ubuntu 18.04, 20.04 or compatible!
but my os is Ubuntu 20.04:
![image](https://github.com/fkie-cad/FACT_docker/assets/11664059/70930dec-0084-48b9-99c9-6a1802ca4730)
so what problem with this?

**Comment by maringuu** [comment]
Solved by: 22e9c88c9000aab2fd173177340b0093173bcb86
