### ISSUE TITLE
Please tell me what's fact password for "ghcr.io/fkie-cad/fact-core-backend:4.0.1" Thanks!

### ISSUE THREAD

**Issue by yujack008** [fkie-cad/FACT_docker#42]
### Your question

i test user fact password 'fact' error!

**Comment by maringuu** [comment]
There is not password.
Why would you need a password, what is your usecase?

Note that you can just use docker to e.g. do ` docker exec -it --user some-user my-container /bin/sh`. To Run a shell as `some-user` in `my-container`.

**Comment by maringuu** [comment]
Please reopen if this does not solve you usecase.
