### ISSUE TITLE
Unsupported Distro Bug

### ISSUE THREAD

**Issue by leo-tanj** [fkie-cad/FACT_docker#44]
When I run the start.py pull, I get this:
![image](https://github.com/fkie-cad/FACT_docker/assets/69200108/d11ab177-f30d-4e4f-a54f-509fcdedc736)

My version of Ubuntu is 22.04.
![image](https://github.com/fkie-cad/FACT_docker/assets/69200108/33155fe3-2f8d-4529-a35e-48a8d7b38558)

When I proceed, I get this:
![image](https://github.com/fkie-cad/FACT_docker/assets/69200108/1f748cad-b1ac-4ca4-aa9e-81f3f7e2954d)

I appreciate any help with this. Thank you!

**Comment by huntercu** [comment]
I encountered the same problem, how to solve it.
